version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bank_reconciliation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 bank_reconciliation.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=bank_reconciliation
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A bank_reconciliation worker -l info
    volumes:
      - .:/app
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=bank_reconciliation
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
