# Generated by Django 6.0.6 on 2026-06-21 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_matching", "0001_initial"),
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsuggestion",
            name="bank_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reconciliation.banktransaction",
            ),
        ),
        migrations.AddField(
            model_name="matchsuggestion",
            name="source_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reconciliation.sourcetransaction",
            ),
        ),
    ]
