# Generated by Django 6.0.6 on 2026-07-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntercompanyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("date", models.DateField()),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("reference", models.CharField(max_length=100)),
                (
                    "from_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ic_from_transactions",
                        to="core.company",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ic_to_transactions",
                        to="core.company",
                    ),
                ),
            ],
        ),
    ]
